configuration: Release
image: Visual Studio 2017

environment:
  PRODUCT_NAME: qufin-api
  sonar_login:
    secure: tJk16EF+JLZI8i3oxJO1/zX/TP15Yd0bo0hgUGJrhAhQyKiU19aFMZx14vloWU0g
  secret_for_snk:
    secure: 9wAuC5ZEdGrfCqltk4Ax6Q==
  COVERALLS_REPO_TOKEN:
    secure: 76mzKeyvLbYy67jTHw4n8mvd5iKrkm+6u5GSqoZLKQHQ3zIAd1oxenl78I0w/xL0

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(GitVersion_InformationalVersion)'
  assembly_version: '$(GitVersion_AssemblySemVer)'
  file_version: '$(GitVersion_AssemblySemVer)'
  informational_version: '$(GitVersion_InformationalVersion)'

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\Users\appveyor\.nuget\packages -> *.csproj
  - C:\Users\appveyor\.sonar\cache
  
install:
  - choco install gitversion.portable -pre -y
  - choco install resharper-clt -y
  - choco install "msbuild-sonarqube-runner" -y
  - nuget install secure-file -ExcludeVersion
  - nuget install OpenCover -ExcludeVersion
  - nuget install coveralls.net -ExcludeVersion
  - secure-file\tools\secure-file -decrypt %APPVEYOR_BUILD_FOLDER%\tools\Key\Key.snk.enc -secret %secret_for_snk%  
  - gitversion /l console /output buildserver

before_build:
  - ps: dotnet restore src\$env:PRODUCT_NAME.sln
  - SonarQube.Scanner.MSBuild.exe begin /k:"%PRODUCT_NAME%" /d:sonar.organization="rombolshak-github" /n:"%PRODUCT_NAME%" /v:"%APPVEYOR_BUILD_VERSION%" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%sonar_login%"

build_script:
  - ps: dotnet build src\$env:PRODUCT_NAME.sln

after_build:
  - ps: inspectcode.exe /o:tools\Build\ReSharperRules\ListOfIssues.xml src\$env:PRODUCT_NAME.sln
  - ps: tools\Build\ReSharperRules\OutputAnalyzeFilter.ps1
  - ps: tools\Build\ReSharperRules\ProblemsChecker.ps1 -pathToFilteredXml tools\Build\ReSharperRules\FilteredListOfIssues.xml

test_script:
  - OpenCover\tools\OpenCover.Console.exe -target:powershell.exe -targetargs:%APPVEYOR_BUILD_FOLDER%\tools\unit_test.ps1 -filter:"+[*]* -[*Tests]*" -register:user -returntargetcode -mergeoutput -output:.\TestResult.xml -oldStyle -searchdirs:APPVEYOR_BUILD_FOLDER\bin\Release\netcoreapp2.0
  
after_test:
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\TestResult.xml
  - MSBuild.SonarQube.Runner.exe end /d:sonar.login=%sonar_login%
  
artifacts:
  - path: bin\Release
